title: Anjam Games
email: anjammorpg@gmail.com
description: >-
  Créatrice de visual novels et jeux narratifs avec Ren'Py. 
  Découvrez mes univers entre mystère, romance et aventure.
baseurl: ""
url: "https://ajam-games.netlify.app"
twitter_username: # à remplir si tu en as un
github_username: anjammorpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections pour tes jeux
collections:
  games:
    output: true
    permalink: /:collection/:name/